- name: Create JIRA Home directory
  become: yes
  file:
    path: "{{ jira_home }}"
    state: directory
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"

- name: Update JIRA Home directory permissions
  become: yes
  file:
    path: "{{ jira_home }}"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0755
    #recurse: yes

- name: Mount JIRA Home Dir on EFS Volume
  become: yes
  mount:
    path: "{{ jira_home }}"
    src: "{{ jira_data_volume_id }}"
    fstype: efs
    opts: tls
    state: mounted

# Check EFS for AWS Backup directory
# Moves files into place
# Remove AWS Backup directory
- include: backup_placement.yml
  when: restore_from_backup

- name: Create JIRA DB
  mysql_db:
    state: present
    name: "{{ jira_db_name }}"
    login_host: "{{ jira_db_endpoint }}"
    login_user: "{{ db_master_user }}"
    login_password: "{{ db_master_password }}"
    collation: utf8_bin
    encoding: utf8

- name: Create MySQL JIRA User
  mysql_user:
    user: "{{ jira_user }}"
    password: "{{ jira_admin_password }}"
    host: "%"
    login_host: "{{ jira_db_endpoint }}"
    login_user: "{{ db_master_user }}"
    login_password: "{{ db_master_password }}"
    priv: "{{ jira_db_name }}.*:{{ jira_db_grants }}"
    update_password: always
    state: present

- name: Update dbconfig.xml file
  template:
    src: dbconfig.xml.j2
    dest: "{{ jira_home }}/dbconfig.xml"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0644

- name: Apply JIRA server.xml template
  template:
    src: "server-{{ jira_version }}.xml.j2"
    dest: "{{ jira_user_home_dir }}/{{ jira_filename }}-{{ jira_version }}-standalone/conf/server.xml"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0755

- name: Create JIRA systemd service script
  template:
    src: jira.service.j2
    dest: /usr/lib/systemd/system/jira.service
    mode: 0644

- name: jira_version
  debug:
    var: jira_version

- name: jira_version float
  debug:
    var: "{{ jira_version | float }}"

- name: Update checkjava script with version from later Jira for OpenJDK compatibility
  become: yes
  copy:
    src: "{{ role_path}}/files/check-java.sh"
    dest: "{{ jira_user_home_dir }}/{{ jira_filename }}-{{ jira_version }}-standalone/bin/check-java.sh"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0755
    backup: yes
  when: jira_version | float >= 7 and jira_version | float < 8