- name: Create JIRA data directory
  become: yes
  file:
    path: "{{ jira_data_dir }}"
    state: directory
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"

- name: Update JIRA data directory permissions
  become: yes
  file:
    path: "{{ jira_data_dir }}"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0755
    recurse: yes

- name: Mount JIRA Data Dir on EFS Volume
  become: yes
  mount:
    path: "{{ jira_data_dir }}"
    src: "{{ jira_data_volume_id }}"
    fstype: efs
    opts: tls
    state: mounted

- name: Create MySQL JIRA User
  mysql_user:
    user: "{{ jira_user }}"
    password: "{{ jira_admin_password }}"
    host: "%"
    login_host: "{{ jira_db_endpoint }}"
    login_user: "{{ db_master_user }}"
    login_password: "{{ db_master_password }}"
    priv: "{{ jira_db_name }}.*:{{ jira_db_grants }}"
    update_password: always
    state: present

- name: Update dbconfig.xml file
  template: 
    src: dbconfig.xml.j2 
    dest: "{{ jira_home }}/dbconfig.xml"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"