- name: Update SSM Agent
  become: yes
  yum:
    name: amazon-ssm-agent
    state: latest

- name: Install additional packages
  become: yes
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - tree
