---
- name: Enable and Start awslogsd service
  become: yes
  systemd:
    state: started
    name: awslogsd
    enabled: yes

- name: Enable and Start jira service
  become: yes
  systemd:
    state: started
    name: jira
    enabled: yes