---
- name: Enable and Start awslogsd service
  become: yes
  systemd:
    state: started
    name: awslogsd
    enabled: yes

- name: Enable and Start jira service
  become: yes
  systemd:
    state: started
    name: jira
    enabled: yes
    daemon_reload: true

- name: Create JIRA systemd service script
  template: 
    src: jira.service.j2 
    dest: /usr/lib/systemd/system/jira.service
  notify: 
    - jira-restart