---
- name: Enable and Start awslogsd service
  become: yes
  systemd:
    state: stopped #started
    name: awslogsd
    enabled: yes

- name: Enable and Start jira service
  become: yes
  systemd:
    state: stopped #started
    name: jira
    enabled: yes
    daemon_reload: true